name: Go
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
      - "**/scoop/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Format
        run: go fmt ./...

      - name: Vet
        run: go vet -v ./...

      - name: Test
        run: go test -v ./...

      - name: Build-lnx-x64
        run: go build -race -ldflags "-s -w -X main.version=${{github.ref_name}} -X main.sha1ver=$GITHUB_SHA -X main.buildTime=$(date '+%Y-%m-%dT%H:%M:%S') -extldflags '-static'"

      - name: Build-win-x64
        if: startsWith(github.ref, 'refs/tags/')
        run: GOOS=windows GOARCH=amd64 go build -ldflags "-s -w -X main.version=${{github.ref_name}} -X main.sha1ver=$GITHUB_SHA -X main.buildTime=$(date '+%Y-%m-%dT%H:%M:%S') -extldflags '-static'"

      - name: Zip
        if: startsWith(github.ref, 'refs/tags/')
        run: tar -czvf ash-${{github.ref_name}}-linux-x64.tar.gz ash ash.config.json res && zip -r ash-${{github.ref_name}}-win-x64.zip ash.exe ash.config.json res

      - name: Hash
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          sha256sum ash-${{github.ref_name}}-linux-x64.tar.gz > ash-${{github.ref_name}}-linux-x64.tar.gz.sha256 &&\
          sha256sum ash-${{github.ref_name}}-win-x64.zip > ash-${{github.ref_name}}-win-x64.zip.sha256

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ash-${{github.ref_name}}-linux-x64.tar.gz
            ash-${{github.ref_name}}-linux-x64.tar.gz.sha256
            ash-${{github.ref_name}}-win-x64.zip
            ash-${{github.ref_name}}-win-x64.zip.sha256
