name: Go

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Format
      run: go fmt ./...
      
    - name: Vet
      run: go vet -v ./...
      
    - name: Test
      run: go test -v ./...

    - name: Build-lnx-x64
      run: go build -race -ldflags "-s -w -X main.version=${{github.ref_name}} -X main.sha1ver=$GITHUB_SHA -X main.buildTime=$(date '+%Y-%m-%dT%H:%M:%S') -extldflags '-static'"

    - name: Build-win-x64
      run: GOOS=windows GOARCH=amd64 go build -ldflags "-s -w -X main.version=${{github.ref_name}} -X main.sha1ver=$GITHUB_SHA -X main.buildTime=$(date '+%Y-%m-%dT%H:%M:%S') -extldflags '-static'"
    
    - name: Create scoop manifest
      run: 'echo { "version": "${{github.ref_name}}", "url": "https://github.com/paolo-dellepiane/ash/releases/download/${{github.ref_name}}/ash-${{github.ref_name}}-win-x64.zip", "bin": "ash.exe" }> ash.json'
    
    - name: Zip
      if: startsWith(github.ref, 'refs/tags/')
      run: tar -czvf ash-${{github.ref_name}}-linux-x64.tar.gz ash ash.config.json && zip -r ash-${{github.ref_name}}-win-x64.zip ash.exe ash.config.json

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ash-${{github.ref_name}}-linux-x64.tar.gz
          ash-${{github.ref_name}}-win-x64.zip
          ash.json
