name: Go

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Format
      run: go fmt ./...
      
    - name: Test
      run: go vet -v ./...
      
    - name: Test
      run: go test -v ./...

    - name: Build-lnx
      run: go build -race -ldflags "-s -w -X main.version=${{github.ref_name}} -X main.sha1ver=$GITHUB_SHA -X main.buildTime=$(date '+%Y-%m-%dT%H:%M:%S') -extldflags '-static'"

    - name: Build-lnx
      run: env GOOS=windows GOARCH=amd64 \
        go build -race -ldflags "-s -w -X main.version=${{github.ref_name}} -X main.sha1ver=$GITHUB_SHA -X main.buildTime=$(date '+%Y-%m-%dT%H:%M:%S') -extldflags '-static'"
      
    - name: Zip
      run: tar -czvf ash-linux-x64.tar.gz ash ash.config.json utils && zip -r ash-win-x64.zip ash.exe ash.config.json utils

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ash-linux-x64.tar.gz
          ash-win-x64.zip
